// Legal wording requires qualified privacy review before merge.
/** Shared wording for public legal pages and the consent dialog. */
export type LegalLanguage = 'en' | 'th';
export type LegalDocument = 'terms' | 'privacy';
type Text = Record<LegalLanguage, string>;
export type LegalSection = { id: string; title: Text; paragraphs?: Text[]; bullets?: Text[] };
const text = (en: string, th: string): Text => ({ en, th });
export const LEGAL_CONTACT = 'Novartis@novartis-decisionlab.firebaseapp.com';
export const legalTitles = { terms: text('Terms of service', 'ข้อกำหนดการใช้งาน'), privacy: text('Privacy policy', 'นโยบายความเป็นส่วนตัว') };
export const legalIntro = {
  terms: text('The rules for using NovarQuiz, managing your account and taking part in quizzes.', 'ข้อกำหนดสำหรับการใช้ NovarQuiz การดูแลบัญชี และการทำแบบทดสอบ'),
  privacy: text('What we collect, how we use it and the choices you have.', 'ข้อมูลที่เราเก็บ วิธีใช้ข้อมูล และสิ่งที่คุณเลือกได้'),
};
export const legalSections: Record<LegalDocument, LegalSection[]> = {
  terms: [
    { id: 'agreement', title: text('Using NovarQuiz', 'การใช้ NovarQuiz'), paragraphs: [text('By creating an account or using NovarQuiz, you agree to these terms. If you do not agree, do not use the service.', 'เมื่อสร้างบัญชีหรือใช้ NovarQuiz ถือว่าคุณยอมรับข้อกำหนดนี้ หากไม่ยอมรับ โปรดงดใช้บริการ')] },
    { id: 'service', title: text('About the service', 'เกี่ยวกับบริการ'), paragraphs: [text('NovarQuiz lets you take quizzes created by administrators, see scores and view leaderboards. Quiz summaries are for learning; they are not health assessments or medical advice.', 'NovarQuiz ให้คุณทำแบบทดสอบที่ผู้ดูแลสร้าง ดูคะแนนและอันดับผู้เล่น สรุปผลใช้เพื่อการเรียนรู้ ไม่ใช่การประเมินสุขภาพหรือคำแนะนำทางการแพทย์')] },
    { id: 'account', title: text('Your account', 'บัญชีของคุณ'), paragraphs: [text('You must be at least 13 to use NovarQuiz. Keep your sign-in details private. You are responsible for activity on your account.', 'ผู้ใช้ต้องมีอายุอย่างน้อย 13 ปี เก็บข้อมูลเข้าสู่ระบบเป็นความลับ และรับผิดชอบการใช้งานในบัญชีของคุณ')] },
    { id: 'use', title: text('What you must not do', 'การใช้งานที่ไม่อนุญาต'), bullets: [text('Use the service for unlawful activities.', 'ใช้บริการเพื่อทำสิ่งที่ผิดกฎหมาย'), text('Access accounts or systems without permission, disrupt the service or exploit security weaknesses.', 'เข้าถึงบัญชีหรือระบบโดยไม่ได้รับอนุญาต รบกวนบริการ หรือใช้ประโยชน์จากช่องโหว่'), text('Upload harmful content, impersonate someone else or provide false information.', 'อัปโหลดเนื้อหาที่เป็นอันตราย แอบอ้างเป็นผู้อื่น หรือให้ข้อมูลเท็จ')] },
    { id: 'content', title: text('Content ownership', 'สิทธิในเนื้อหา'), paragraphs: [text('NovarQuiz content and features are protected by intellectual property law. Do not reproduce them without written permission.', 'เนื้อหาและฟังก์ชันของ NovarQuiz ได้รับความคุ้มครองตามกฎหมายทรัพย์สินทางปัญญา ห้ามทำซ้ำโดยไม่ได้รับอนุญาตเป็นลายลักษณ์อักษร')] },
    { id: 'data', title: text('Your personal data', 'ข้อมูลส่วนบุคคลของคุณ'), paragraphs: [text('Our privacy policy explains how we use personal data under Thailand’s Personal Data Protection Act (PDPA). Account processing is required to provide an account. Questionnaire analytics and marketing consent are optional.', 'นโยบายความเป็นส่วนตัวอธิบายการใช้ข้อมูลตามกฎหมายคุ้มครองข้อมูลส่วนบุคคลของไทย (PDPA) การใช้ข้อมูลเพื่อให้บริการบัญชีจำเป็นต่อการมีบัญชี ส่วนการวิเคราะห์แบบสอบถามและการตลาดเป็นทางเลือก'), text('You can withdraw consent for account processing by deleting your account. Optional consent can be withdrawn separately, as described in the privacy policy.', 'คุณถอนความยินยอมในการใช้ข้อมูลเพื่อให้บริการบัญชีได้โดยลบบัญชี ส่วนความยินยอมที่เป็นทางเลือกถอนแยกได้ตามนโยบายความเป็นส่วนตัว')] },
    { id: 'availability', title: text('Service availability', 'ความพร้อมของบริการ'), paragraphs: [text('The service is provided as available, without warranties. We cannot guarantee that it will always be available or free of errors.', 'บริการให้ใช้งานตามสภาพที่มี โดยไม่มีการรับประกัน เราไม่รับประกันว่าบริการจะพร้อมใช้งานตลอดเวลาหรือไม่มีข้อผิดพลาด')] },
    { id: 'liability', title: text('Limits on liability', 'ข้อจำกัดความรับผิด'), paragraphs: [text('To the extent allowed by law, NovarQuiz is not liable for indirect, incidental, special, consequential or punitive damages arising from use of the service.', 'ภายในขอบเขตที่กฎหมายอนุญาต NovarQuiz ไม่รับผิดชอบความเสียหายทางอ้อม ความเสียหายที่เกิดขึ้นโดยบังเอิญ ความเสียหายพิเศษ ความเสียหายสืบเนื่อง หรือค่าเสียหายเชิงลงโทษที่เกิดจากการใช้บริการ')] },
    { id: 'updates', title: text('Changes to these terms', 'การเปลี่ยนแปลงข้อกำหนด'), paragraphs: [text('We may update these terms without prior notice. Updates take effect when published. Continuing to use the service means you accept the updated terms.', 'เราอาจปรับข้อกำหนดโดยไม่แจ้งล่วงหน้า ข้อกำหนดใหม่มีผลเมื่อเผยแพร่ การใช้บริการต่อถือว่ายอมรับข้อกำหนดที่ปรับปรุงแล้ว')] },
    { id: 'law', title: text('Applicable law', 'กฎหมายที่ใช้บังคับ'), paragraphs: [text('These terms are governed by the laws of Thailand.', 'ข้อกำหนดนี้อยู่ภายใต้กฎหมายของประเทศไทย')] },
  ],
  privacy: [
    { id: 'controller', title: text('Who is responsible for your data', 'ผู้รับผิดชอบข้อมูลของคุณ'), paragraphs: [text(`NovarQuiz is the data controller. For privacy questions or requests, contact ${LEGAL_CONTACT}.`, `NovarQuiz เป็นผู้ควบคุมข้อมูลส่วนบุคคล หากมีคำถามหรือต้องการใช้สิทธิ ติดต่อ ${LEGAL_CONTACT}`)] },
    { id: 'collected', title: text('What we collect', 'ข้อมูลที่เราเก็บ'), bullets: [text('Account details: email, display name and profile photo.', 'ข้อมูลบัญชี: อีเมล ชื่อที่แสดง และรูปโปรไฟล์'), text('Questionnaire answers: first and last name, plus optional age, gender, weight, height and activity level. Your name becomes your default profile name.', 'คำตอบแบบสอบถาม: ชื่อและนามสกุล ส่วนอายุ เพศ น้ำหนัก ส่วนสูง และระดับกิจกรรมไม่บังคับกรอก ชื่อจะใช้เป็นชื่อโปรไฟล์เริ่มต้น'), text('Quiz activity: selected answers, scores, participation, streaks and completion details.', 'ข้อมูลการทำแบบทดสอบ: คำตอบที่เลือก คะแนน การเข้าร่วม จำนวนข้อที่ตอบถูกต่อเนื่อง และข้อมูลการทำเสร็จ'), text('Technical details: browser type, session cookies and the IP address recorded with consent as evidence.', 'ข้อมูลทางเทคนิค: ประเภทเบราว์เซอร์ คุกกี้เข้าสู่ระบบ และ IP address ที่บันทึกพร้อมความยินยอมเพื่อเป็นหลักฐาน')] },
    { id: 'uses', title: text('How we use it', 'เราใช้ข้อมูลอย่างไร'), paragraphs: [text('We use account and quiz data to sign you in, calculate scores and rankings, save quiz history, provide statistics, improve the service and meet data-protection obligations. Our stated basis for processing is your consent under section 19 of the PDPA.', 'เราใช้ข้อมูลบัญชีและแบบทดสอบเพื่อเข้าสู่ระบบ คำนวณคะแนนและอันดับ เก็บประวัติ แสดงสถิติ ปรับปรุงบริการ และปฏิบัติตามหน้าที่ด้านการคุ้มครองข้อมูล โดยอาศัยความยินยอมตามมาตรา 19 ของ PDPA'), text('Questionnaire answers appear in administrator charts only if you opt in. Charts count each account once and do not show names or account identifiers. These answers are not sent to the AI summary service.', 'คำตอบแบบสอบถามใช้ในกราฟสำหรับผู้ดูแลเฉพาะเมื่อคุณยินยอม กราฟนับแต่ละบัญชีครั้งเดียวและไม่แสดงชื่อหรือรหัสบัญชี ข้อมูลแบบสอบถามไม่ส่งไปยังบริการสรุปจาก AI')] },
    { id: 'ai', title: text('AI quiz summaries', 'สรุปผลแบบทดสอบจาก AI'), paragraphs: [text('If there is no matching saved summary, we may send selected quiz answers, the answer key and quiz explanations to Google Gemini. We do not include your name, email, account ID or scores in that request.', 'หากไม่มีสรุปที่บันทึกไว้ตรงกับคำตอบ เราอาจส่งคำตอบที่เลือก เฉลย และคำอธิบายในแบบทดสอบไปยัง Google Gemini โดยไม่ส่งชื่อ อีเมล รหัสบัญชี หรือคะแนน'), text('The answer pattern and draft summary are saved using a hashed key for review and reuse. People with closely matching answers may receive the same summary. Unreviewed summaries are labelled. Approval changes that label; rejected summaries are hidden.', 'รูปแบบคำตอบและสรุปฉบับร่างบันทึกด้วยรหัสแฮชเพื่อรอตรวจและใช้ซ้ำ ผู้ที่ตอบใกล้เคียงกันอาจได้รับสรุปเดียวกัน สรุปที่ยังไม่ตรวจมีป้ายแจ้ง เมื่ออนุมัติจะเปลี่ยนป้าย ส่วนสรุปที่ไม่อนุมัติจะถูกซ่อน')] },
    { id: 'visibility', title: text('Who can see your information', 'ใครเห็นข้อมูลของคุณได้บ้าง'), bullets: [text('Administrators can access the personal data collected by NovarQuiz, including account details, questionnaire answers, quiz responses and scores.', 'ผู้ดูแลเข้าถึงข้อมูลส่วนบุคคลที่ NovarQuiz เก็บ เช่น ข้อมูลบัญชี คำตอบแบบสอบถาม คำตอบในแบบทดสอบ และคะแนน'), text('Other users and visitors can see your display name, profile photo and results on session leaderboards, including score, rank, correct answers, streak and completion time. They cannot see your email or individual quiz responses.', 'ผู้ใช้คนอื่นและผู้เข้าชมเห็นชื่อที่แสดง รูปโปรไฟล์ และผลบนอันดับผู้เล่น เช่น คะแนน อันดับ จำนวนข้อที่ตอบถูก จำนวนข้อที่ตอบถูกต่อเนื่อง และเวลาที่ทำเสร็จ แต่ไม่เห็นอีเมลหรือคำตอบรายข้อ')] },
    { id: 'choices', title: text('Your consent choices', 'การเลือกให้ความยินยอม'), paragraphs: [text('Accepting these documents enables the account processing needed to provide the service. Marketing follow-up for product updates and promotions remains optional.', 'การยอมรับเอกสารนี้ให้ความยินยอมใช้ข้อมูลที่จำเป็นต่อการให้บริการบัญชี ส่วนการติดตามทางการตลาดเพื่อแจ้งผลิตภัณฑ์และโปรโมชันเป็นทางเลือก'), text('You can edit questionnaire answers and withdraw questionnaire analytics consent in Profile. Withdrawal excludes your answers from subsequent chart queries. Contact us to update other optional consent, or delete your account to withdraw account-processing consent.', 'แก้ไขคำตอบแบบสอบถามและถอนความยินยอมในการวิเคราะห์ได้ที่หน้าโปรไฟล์ หลังถอน คำตอบจะไม่รวมในกราฟที่เรียกดูครั้งถัดไป ติดต่อเราเพื่อแก้ไขความยินยอมทางเลือกอื่น หรือลบบัญชีเพื่อถอนความยินยอมในการใช้ข้อมูลเพื่อให้บริการบัญชี'), text('Withdrawal takes effect immediately. It does not affect processing that was lawful before withdrawal.', 'การถอนความยินยอมมีผลทันที และไม่กระทบการใช้ข้อมูลที่ชอบด้วยกฎหมายก่อนถอน')] },
    { id: 'retention', title: text('How long we keep data', 'เราเก็บข้อมูลนานแค่ไหน'), paragraphs: [text('We keep personal data while your account is active. After account deletion, personal data is permanently removed within 30 days. Consent records are kept for 3 years as evidence of consent.', 'เราเก็บข้อมูลส่วนบุคคลขณะที่บัญชียังใช้งาน หลังลบบัญชี ข้อมูลส่วนบุคคลจะถูกลบถาวรภายใน 30 วัน ส่วนหลักฐานความยินยอมเก็บไว้ 3 ปี')] },
    { id: 'providers', title: text('Service providers and data transfers', 'ผู้ให้บริการและการส่งข้อมูล'), paragraphs: [text('We do not sell your data. We use the providers below, which may process data outside Thailand. Cross-border transfers are subject to the PDPA.', 'เราไม่ขายข้อมูลของคุณ ผู้ให้บริการต่อไปนี้อาจประมวลผลข้อมูลนอกประเทศไทย การส่งข้อมูลข้ามประเทศอยู่ภายใต้ PDPA')], bullets: [text('Google Firebase: sign-in, real-time data and file storage.', 'Google Firebase: การเข้าสู่ระบบ ข้อมูลแบบเรียลไทม์ และพื้นที่เก็บไฟล์'), text('Neon / PostgreSQL: quiz data and user profiles.', 'Neon / PostgreSQL: ข้อมูลแบบทดสอบและโปรไฟล์ผู้ใช้'), text('Google Gemini: draft summaries from quiz answers and explanations.', 'Google Gemini: สร้างสรุปฉบับร่างจากคำตอบและคำอธิบายในแบบทดสอบ')] },
    { id: 'rights', title: text('Your data rights', 'สิทธิในข้อมูลของคุณ'), paragraphs: [text(`You can request access, correction, deletion or a portable copy of your data, ask us to restrict processing, object where applicable or withdraw consent. Contact ${LEGAL_CONTACT} or use the relevant Profile settings. We respond to requests within 30 days.`, `คุณขอเข้าถึง แก้ไข ลบ หรือรับสำเนาข้อมูลเพื่อโอนย้าย ขอจำกัดการใช้ข้อมูล คัดค้านตามเงื่อนไขที่กฎหมายกำหนด หรือถอนความยินยอมได้ ติดต่อ ${LEGAL_CONTACT} หรือใช้การตั้งค่าที่เกี่ยวข้องในหน้าโปรไฟล์ เราตอบคำขอภายใน 30 วัน`)] },
    { id: 'cookies', title: text('Cookies', 'คุกกี้'), paragraphs: [text('We use an essential session cookie to keep you signed in. It uses HttpOnly, Secure and SameSite=Lax protections. We do not use advertising or tracking cookies.', 'เราใช้คุกกี้ session ที่จำเป็นเพื่อให้คุณอยู่ในระบบ โดยใช้การป้องกัน HttpOnly, Secure และ SameSite=Lax ไม่ใช้คุกกี้โฆษณาหรือติดตาม')] },
    { id: 'security', title: text('Keeping data secure', 'การรักษาความปลอดภัยของข้อมูล'), paragraphs: [text('We use TLS encryption, storage encryption through Firebase and Neon, and access controls based on user roles. Firebase handles passwords; NovarQuiz does not store them directly.', 'เราใช้การเข้ารหัส TLS การเข้ารหัสข้อมูลที่เก็บผ่าน Firebase และ Neon และกำหนดสิทธิ์ตามบทบาทผู้ใช้ Firebase จัดการรหัสผ่าน โดย NovarQuiz ไม่เก็บรหัสผ่านโดยตรง')] },
    { id: 'children', title: text('Children under 13', 'เด็กอายุต่ำกว่า 13 ปี'), paragraphs: [text('NovarQuiz is not intended for children under 13. Contact us if you believe a child has provided personal data so we can remove it.', 'NovarQuiz ไม่ได้ให้บริการสำหรับเด็กอายุต่ำกว่า 13 ปี หากทราบว่าเด็กส่งข้อมูลส่วนบุคคลให้เรา โปรดติดต่อเพื่อให้ลบข้อมูล')] },
    { id: 'updates', title: text('Changes to this policy', 'การเปลี่ยนแปลงนโยบาย'), paragraphs: [text('We may update this policy without prior notice. Updates take effect when published. You can request earlier versions by contacting us.', 'เราอาจปรับนโยบายโดยไม่แจ้งล่วงหน้า นโยบายใหม่มีผลเมื่อเผยแพร่ คุณขอเอกสารฉบับก่อนหน้าได้โดยติดต่อเรา')] },
  ],
};
