
import { Pool } from 'pg';
import * as fs from 'fs';
import * as path from 'path';
import { getDatabaseConnectionOptions } from '../lib/db/config';
import * as dotenv from 'dotenv';

// Load .env.neon specifically
dotenv.config({ path: '.env.neon' });

const pool = new Pool(getDatabaseConnectionOptions());

const TABLES = [
  'quizzes',
  'questions',
  'choices',
  'question_connections',
  'user_answers',
  'leaderboard_entries',
  'sessions'
];

async function exportData() {
  const outputFilePath = path.join(process.cwd(), 'db', 'neon_dump.sql');
  const stream = fs.createWriteStream(outputFilePath);

  stream.write('-- Neon Database Dump\n');
  stream.write('-- Generated by export-neon.ts\n\n');
  stream.write('BEGIN;\n\n');

  // Disable triggers to avoid FK issues during data load
  stream.write('SET session_replication_role = \'replica\';\n\n');

  try {
    for (const table of TABLES) {
      console.log(`Exporting table: ${table}...`);
      
      // Get table data
      const { rows, fields } = await pool.query(`SELECT * FROM ${table}`);
      
      if (rows.length === 0) {
        stream.write(`-- No data for ${table}\n\n`);
        continue;
      }

      stream.write(`-- Data for ${table}\n`);
      const columns = fields.map(f => f.name).join(', ');
      
      for (const row of rows) {
        const values = fields.map(f => {
          const val = row[f.name];
          if (val === null) return 'NULL';
          if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
          if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
          if (val instanceof Date) return `'${val.toISOString()}'`;
          if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
          return val;
        }).join(', ');
        
        stream.write(`INSERT INTO ${table} (${columns}) VALUES (${values});\n`);
      }
      stream.write('\n');
    }

    stream.write('SET session_replication_role = \'origin\';\n');
    stream.write('COMMIT;\n');
    console.log(`Export complete! Saved to ${outputFilePath}`);
  } catch (err) {
    console.error('Export failed:', err);
  } finally {
    stream.end();
    await pool.end();
  }
}

exportData();
